=== giver-kdk/Web-Development/AJAX-and-XML/XML/XSD/emp_struct.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XSD(XML Schema Definition) defines the XML structure as DTD but it is more powerful -->
<!-- Use 'xs:' prefix to write XSD rule -->
<!-- 'xmlns' means XML Namespace and the link provides standard namespace-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="employee_list">
		<!-- Means the parent element is a complex element -->
		<xs:complexType>
			<!-- Means there are lists of elements -->
			<xs:sequence >
				<xs:element name="employee"  maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- Defines element data type -->
							<xs:element name="name" type="xs:string"/>
							<xs:element name="salary" type="xs:integer"/>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="contact" type="xs:integer"/>
						</xs:sequence>
						<!-- Defines the attribute data type and says it's compulsary -->
						<xs:attribute name="id" use="required" type="xs:integer"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== giver-kdk/Web-Development/AJAX-and-XML/XML/XSD/employee.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Linking XSD through the root element -->
<!-- Here, 'xmlns:xsi' provides standard element and data types -->
<employee_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./emp_struct.xsd"> 
    <employee id="1">
        <name>Smith Nepal</name>
        <salary>40000</salary>
        <email>smithnepal1234@gmail.com</email>
        <contact>9800000000</contact>
    </employee>
    <employee id="2">
        <name>Rameshwor Nepal</name>
        <salary>80000</salary>
        <email>rameshwor1234@gmail.com</email>
        <contact>9700000000</contact>
    </employee>
    <employee id="3">
        <name>Alex KC</name>
        <salary>80000</salary>
        <email>rameshwor1234@gmail.com</email>
        <contact>9700000000</contact>
    </employee>
</employee_list>
